# 数据配置
data:
  historical_transactions_path: "data/historical_transactions.csv"
  weather_info_path: "data/weather_info.csv"
  output_base_path: "output"
  model_save_path: "models"
  # 支持批量处理多商品/门店
  product_store_pairs:
    - product_code: "4701098"
      store_code: "205625"
  # 数据过滤规则
  min_data_days: 14  # 最小数据量（天）
  sales_qty_min: 0   # 最小销量（过滤退货）

# Prophet模型配置
prophet:
  seasonality_mode: "multiplicative"
  yearly_seasonality: true
  weekly_seasonality: true
  daily_seasonality: false
  holidays_prior_scale: 10
  seasonality_prior_scale: 10
  changepoint_prior_scale: 0.05
  n_changepoints: 25
  interval_width: 0.95
  mcmc_samples: 0
#  forecast_periods: 1  # 预测天数
#  forecast_freq: "D"

# 特征工程配置
feature:
  lag_days: [1, 3, 7, 14, 30]          # 滞后特征窗口
  rolling_windows: [7, 14, 30]         # 滚动特征窗口
  scaler_columns: ["年份", "温度", "最高温度", "最低温度", "温度差"]  # 标准化特征
  # 交互特征防除0阈值
  discount_rate_min: 1e-3